# Generated by Django 4.1.1 on 2022-10-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=200)),
                ('Last', models.IntegerField(default=0)),
                ('Change', models.IntegerField(default=0)),
                ('Changeperc', models.IntegerField(default=0)),
                ('Close', models.IntegerField(default=0)),
                ('High', models.IntegerField(default=0)),
                ('Low', models.IntegerField(default=0)),
                ('LastTrade', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
