# Generated by Django 4.1.1 on 2022-10-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_statslist_delete_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statslist',
            old_name='Change',
            new_name='change',
        ),
        migrations.RenameField(
            model_name='statslist',
            old_name='Changeperc',
            new_name='changeperc',
        ),
        migrations.RenameField(
            model_name='statslist',
            old_name='Close',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='statslist',
            old_name='High',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='statslist',
            old_name='Last',
            new_name='last',
        ),
        migrations.RenameField(
            model_name='statslist',
            old_name='LastTrade',
            new_name='lasttrade',
        ),
        migrations.RenameField(
            model_name='statslist',
            old_name='Low',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='statslist',
            old_name='Symbol',
            new_name='symbol',
        ),
    ]
